# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-05 19:31
from __future__ import unicode_literals

from django.db import migrations


DEFAULT_REALM_ID = '17a21472-c8ff-4fab-a8ce-56dfba40c423'
DEFAULT_ORGANIZATION_ID = '18b66bec-1a7a-48ff-b517-28ac7762ff1a'


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL([
            "INSERT INTO main_realm (id, name) VALUES ('%s', 'default');" %
            DEFAULT_REALM_ID.replace('-', ''),
        ]),
        migrations.RunSQL([
            "INSERT INTO main_organization (id, name) VALUES ('%s', 'default');" %
            DEFAULT_ORGANIZATION_ID.replace('-', ''),
        ]),
    ]
