# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-23 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180405_1931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='externalauthentication',
            old_name='url',
            new_name='app_exposed_url',
        ),
        migrations.AddField(
            model_name='externalauthentication',
            name='user_exposed_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
