#!/bin/sh

cd /app

mkdir -p /tmp/db
python3 manage.py migrate
chmod -R a+rw /tmp/db

python3 manage.py collectstatic --noinput

export UWSGI_UID=${UWSGI_UID:-nobody}
export UWSGI_GID=${UWSGI_GID:-nogroup}
export UWSGI_MODULE=${UWSGI_MODULE:-authserv.wsgi}
export UWSGI_WORKERS=${UWSGI_WORKERS:-1}

python3 manage.py runuwsgi
